name: FancyKandi
favicon: null
layout_spectrum: 0.7452
typography_spectrum: 0.1443
title: FancyKandi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c7c4bf'
    - '#fefefc'
    - '#857f70'
    - '#565858'
  brandStrength: 1
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
