name: FancyKandi
favicon: null
layout_spectrum: 0.13534549390897155
typography_spectrum: 0.22352529037743807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c7c4bf'
    - '#fefefc'
    - '#857f70'
    - '#565858'
  brandStrength: 0.875
  lightness: 0.6687925735022873
  saturation: 0.6401993038598448
  rhythmicContrast: 0.5200315350666642
purpose: []
